import { Product } from "./firestore-setup";

export const mockProducts: Omit<Product, "id">[] = [

  // ── MINIMALISTISK (10) — beige / vit / svart ─────────────────────────────

  {
    brand: "COS",
    name: "Oversized bomullsskjorta",
    price: 590,
    imageUrl: "https://placehold.co/400x500/F5F0E8/2C2C2C?text=Oversized+bomullsskjorta",
    category: "top",
    style: ["Minimalistisk", "Skandinavisk"],
    colors: ["vit", "cremevit"],
    gender: "dam",
    condition: "new",
    isSecondHand: false,
    link: "https://www.cosstores.com",
  },
  {
    brand: "COS",
    name: "Straight-cut linnebyxor",
    price: 890,
    imageUrl: "https://placehold.co/400x500/F5F0E8/2C2C2C?text=Straight-cut+linnebyxor",
    category: "bottom",
    style: ["Minimalistisk", "Skandinavisk"],
    colors: ["beige", "sand"],
    gender: "unisex",
    condition: "new",
    isSecondHand: false,
    link: "https://www.cosstores.com",
  },
  {
    brand: "Arket",
    name: "Merino crewneck-tröja",
    price: 1200,
    imageUrl: "https://placehold.co/400x500/F5F0E8/2C2C2C?text=Merino+crewneck-tröja",
    category: "top",
    style: ["Minimalistisk", "Klassisk"],
    colors: ["svart"],
    gender: "herr",
    condition: "new",
    isSecondHand: false,
    link: "https://www.arket.com",
  },
  {
    brand: "Arket",
    name: "Straight-leg svarta jeans",
    price: 1100,
    imageUrl: "https://placehold.co/400x500/F5F0E8/2C2C2C?text=Straight-leg+svarta+jeans",
    category: "bottom",
    style: ["Minimalistisk", "Klassisk"],
    colors: ["svart", "mörkgrå"],
    gender: "herr",
    condition: "new",
    isSecondHand: false,
    link: "https://www.arket.com",
  },
  {
    brand: "Arket",
    name: "Ullkappa i camelton",
    price: 3800,
    imageUrl: "https://placehold.co/400x500/F5F0E8/2C2C2C?text=Ullkappa+i+camelton",
    category: "outerwear",
    style: ["Minimalistisk", "Klassisk"],
    colors: ["beige", "camel"],
    gender: "dam",
    condition: "new",
    isSecondHand: false,
    link: "https://www.arket.com",
  },
  {
    brand: "H&M",
    name: "Vit linneblus",
    price: 299,
    imageUrl: "https://placehold.co/400x500/F5F0E8/2C2C2C?text=Vit+linneblus",
    category: "top",
    style: ["Minimalistisk"],
    colors: ["vit"],
    gender: "dam",
    condition: "new",
    isSecondHand: false,
    link: "https://www.hm.com",
  },
  {
    brand: "Totême",
    name: "Midi-klänning i silke",
    price: 890,
    originalPrice: 2800,
    imageUrl: "https://placehold.co/400x500/F5F0E8/2C2C2C?text=Midi-klänning+i+silke",
    category: "dress",
    style: ["Minimalistisk", "Skandinavisk"],
    colors: ["beige", "elfenben"],
    gender: "dam",
    condition: "like new",
    isSecondHand: true,
    link: "https://www.sellpy.se",
  },
  {
    brand: "COS",
    name: "Longline blazer svart",
    price: 750,
    originalPrice: 2200,
    imageUrl: "https://placehold.co/400x500/F5F0E8/2C2C2C?text=Longline+blazer+svart",
    category: "outerwear",
    style: ["Minimalistisk"],
    colors: ["svart"],
    gender: "unisex",
    condition: "good",
    isSecondHand: true,
    link: "https://www.tradera.com",
  },
  {
    brand: "& Other Stories",
    name: "Läderloafers i beige",
    price: 1490,
    imageUrl: "https://placehold.co/400x500/F5F0E8/2C2C2C?text=Läderloafers+i+beige",
    category: "shoes",
    style: ["Minimalistisk", "Klassisk"],
    colors: ["beige", "nude"],
    gender: "dam",
    condition: "new",
    isSecondHand: false,
    link: "https://www.stories.com",
  },
  {
    brand: "Acne Studios",
    name: "Cashmere-tröja i beige",
    price: 1200,
    originalPrice: 4500,
    imageUrl: "https://placehold.co/400x500/F5F0E8/2C2C2C?text=Cashmere-tröja+i+beige",
    category: "top",
    style: ["Minimalistisk"],
    colors: ["beige", "grädde"],
    gender: "unisex",
    condition: "like new",
    isSecondHand: true,
    link: "https://www.sellpy.se",
  },

  // ── VINTAGE (10) — brun / orange / mörkgrön ──────────────────────────────

  {
    brand: "Beyond Retro",
    name: "Manchesterjacka mörkgrön",
    price: 650,
    originalPrice: 1200,
    imageUrl: "https://placehold.co/400x500/C4A882/FFFFFF?text=Manchesterjacka+mörkgrön",
    category: "outerwear",
    style: ["Vintage"],
    colors: ["mörkgrön", "brun"],
    gender: "unisex",
    condition: "good",
    isSecondHand: true,
    link: "https://www.beyondretro.com",
  },
  {
    brand: "Levi's",
    name: "501 Original Jeans",
    price: 480,
    originalPrice: 1099,
    imageUrl: "https://placehold.co/400x500/C4A882/FFFFFF?text=501+Original+Jeans",
    category: "bottom",
    style: ["Vintage", "Klassisk"],
    colors: ["brun", "urblekt"],
    gender: "unisex",
    condition: "good",
    isSecondHand: true,
    link: "https://www.tradera.com",
  },
  {
    brand: "Ralph Lauren",
    name: "Flanellskjorta brun-orange",
    price: 420,
    originalPrice: 1200,
    imageUrl: "https://placehold.co/400x500/C4A882/FFFFFF?text=Flanellskjorta+brun-orange",
    category: "top",
    style: ["Vintage", "Klassisk"],
    colors: ["brun", "orange", "rost"],
    gender: "herr",
    condition: "good",
    isSecondHand: true,
    link: "https://www.sellpy.se",
  },
  {
    brand: "Wrangler",
    name: "Western-skjorta i brun",
    price: 350,
    originalPrice: 899,
    imageUrl: "https://placehold.co/400x500/C4A882/FFFFFF?text=Western-skjorta+i+brun",
    category: "top",
    style: ["Vintage"],
    colors: ["brun", "orange"],
    gender: "herr",
    condition: "good",
    isSecondHand: true,
    link: "https://www.tradera.com",
  },
  {
    brand: "Vintage",
    name: "Corduroy-byxor mörkgrön",
    price: 380,
    imageUrl: "https://placehold.co/400x500/C4A882/FFFFFF?text=Corduroy-byxor+mörkgrön",
    category: "bottom",
    style: ["Vintage", "Bohemisk"],
    colors: ["mörkgrön"],
    gender: "dam",
    condition: "good",
    isSecondHand: true,
    link: "https://www.sellpy.se",
  },
  {
    brand: "Levi's",
    name: "Trucker-jacka mörkgrön",
    price: 590,
    originalPrice: 1499,
    imageUrl: "https://placehold.co/400x500/C4A882/FFFFFF?text=Trucker-jacka+mörkgrön",
    category: "outerwear",
    style: ["Vintage", "Klassisk"],
    colors: ["mörkgrön", "brun"],
    gender: "unisex",
    condition: "like new",
    isSecondHand: true,
    link: "https://www.tradera.com",
  },
  {
    brand: "Vintage",
    name: "Slip-klänning i rost",
    price: 290,
    imageUrl: "https://placehold.co/400x500/C4A882/FFFFFF?text=Slip-klänning+i+rost",
    category: "dress",
    style: ["Vintage", "Romantisk"],
    colors: ["orange", "rost", "brun"],
    gender: "dam",
    condition: "good",
    isSecondHand: true,
    link: "https://www.sellpy.se",
  },
  {
    brand: "Dr. Martens",
    name: "1460 boots brun läder",
    price: 1699,
    imageUrl: "https://placehold.co/400x500/C4A882/FFFFFF?text=1460+boots+brun+läder",
    category: "shoes",
    style: ["Vintage", "Streetwear"],
    colors: ["brun"],
    gender: "unisex",
    condition: "new",
    isSecondHand: false,
    link: "https://www.drmartens.com",
  },
  {
    brand: "Dickies",
    name: "Carpenter-byxor mörkgrön",
    price: 699,
    imageUrl: "https://placehold.co/400x500/C4A882/FFFFFF?text=Carpenter-byxor+mörkgrön",
    category: "bottom",
    style: ["Vintage", "Streetwear"],
    colors: ["mörkgrön"],
    gender: "herr",
    condition: "new",
    isSecondHand: false,
    link: "https://www.dickies.com",
  },
  {
    brand: "Carhartt WIP",
    name: "OG Active-jacka brun",
    price: 2200,
    imageUrl: "https://placehold.co/400x500/C4A882/FFFFFF?text=OG+Active-jacka+brun",
    category: "outerwear",
    style: ["Vintage", "Streetwear"],
    colors: ["brun", "orange"],
    gender: "herr",
    condition: "new",
    isSecondHand: false,
    link: "https://www.carhartt-wip.com",
  },

  // ── STREETWEAR (10) — svart / grå / vit ──────────────────────────────────

  {
    brand: "Nike",
    name: "Tech Fleece hoodie svart",
    price: 1299,
    imageUrl: "https://placehold.co/400x500/2C2C2C/FFFFFF?text=Tech+Fleece+hoodie+svart",
    category: "top",
    style: ["Streetwear", "Sportig"],
    colors: ["svart", "grå"],
    gender: "unisex",
    condition: "new",
    isSecondHand: false,
    link: "https://www.nike.com",
  },
  {
    brand: "Adidas",
    name: "Track pants svart-vit",
    price: 799,
    imageUrl: "https://placehold.co/400x500/2C2C2C/FFFFFF?text=Track+pants+svart-vit",
    category: "bottom",
    style: ["Streetwear", "Sportig"],
    colors: ["svart", "vit"],
    gender: "unisex",
    condition: "new",
    isSecondHand: false,
    link: "https://www.adidas.com",
  },
  {
    brand: "Supreme",
    name: "Box Logo tee vit",
    price: 890,
    originalPrice: 1500,
    imageUrl: "https://placehold.co/400x500/2C2C2C/FFFFFF?text=Box+Logo+tee+vit",
    category: "top",
    style: ["Streetwear"],
    colors: ["vit", "svart"],
    gender: "unisex",
    condition: "good",
    isSecondHand: true,
    link: "https://www.tradera.com",
  },
  {
    brand: "Stüssy",
    name: "Oversized hoodie grå",
    price: 1100,
    imageUrl: "https://placehold.co/400x500/2C2C2C/FFFFFF?text=Oversized+hoodie+grå",
    category: "top",
    style: ["Streetwear"],
    colors: ["grå", "mörkgrå"],
    gender: "unisex",
    condition: "new",
    isSecondHand: false,
    link: "https://www.stussy.com",
  },
  {
    brand: "Jordan",
    name: "Air Jordan 1 svart-vit",
    price: 1899,
    imageUrl: "https://placehold.co/400x500/2C2C2C/FFFFFF?text=Air+Jordan+1+svart-vit",
    category: "shoes",
    style: ["Streetwear"],
    colors: ["svart", "vit"],
    gender: "herr",
    condition: "new",
    isSecondHand: false,
    link: "https://www.nike.com/jordan",
  },
  {
    brand: "Weekday",
    name: "Baggy cargo-byxor svart",
    price: 699,
    imageUrl: "https://placehold.co/400x500/2C2C2C/FFFFFF?text=Baggy+cargo-byxor+svart",
    category: "bottom",
    style: ["Streetwear"],
    colors: ["svart"],
    gender: "herr",
    condition: "new",
    isSecondHand: false,
    link: "https://www.weekday.com",
  },
  {
    brand: "Palace",
    name: "Track jacket grå-svart",
    price: 750,
    originalPrice: 2200,
    imageUrl: "https://placehold.co/400x500/2C2C2C/FFFFFF?text=Track+jacket+grå-svart",
    category: "outerwear",
    style: ["Streetwear"],
    colors: ["grå", "svart", "vit"],
    gender: "herr",
    condition: "like new",
    isSecondHand: true,
    link: "https://www.tradera.com",
  },
  {
    brand: "Champion",
    name: "Reverse Weave sweatshirt",
    price: 450,
    originalPrice: 999,
    imageUrl: "https://placehold.co/400x500/2C2C2C/FFFFFF?text=Reverse+Weave+sweatshirt",
    category: "top",
    style: ["Streetwear", "Klassisk"],
    colors: ["grå"],
    gender: "dam",
    condition: "good",
    isSecondHand: true,
    link: "https://www.sellpy.se",
  },
  {
    brand: "New Balance",
    name: "550 sneakers vit-grå",
    price: 1299,
    imageUrl: "https://placehold.co/400x500/2C2C2C/FFFFFF?text=550+sneakers+vit-grå",
    category: "shoes",
    style: ["Streetwear", "Sportig"],
    colors: ["vit", "grå"],
    gender: "dam",
    condition: "new",
    isSecondHand: false,
    link: "https://www.newbalance.com",
  },
  {
    brand: "Carhartt WIP",
    name: "Windbreaker svart",
    price: 680,
    originalPrice: 1800,
    imageUrl: "https://placehold.co/400x500/2C2C2C/FFFFFF?text=Windbreaker+svart",
    category: "outerwear",
    style: ["Streetwear", "Vintage"],
    colors: ["svart", "vit"],
    gender: "dam",
    condition: "like new",
    isSecondHand: true,
    link: "https://www.tradera.com",
  },
];
